import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { BasketProvider } from '@/context/basket-context';
import { FloatingBasketSummary } from '@/components/floating-basket-summary';
import { NotificationCenter } from '@/components/notification-center';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#2563eb" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="apple-mobile-web-app-title" content="Market Karşılaştırma" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <BasketProvider>
          <header className="bg-white border-b sticky top-0 z-50">
            <div className="container mx-auto px-4 h-16 flex items-center justify-between">
              <div className="flex items-center gap-6">
                <a href="/" className="text-xl font-bold text-blue-600 hover:opacity-80 transition-opacity">
                  Market Karşılaştırma
                </a>
                <a href="/alarms" className="hidden md:block text-sm font-medium text-gray-600 hover:text-blue-600 transition-colors">
                  🔔 Fiyat Alarmları
                </a>
                <NotificationCenter />
              </div>
              {/* Future: Add Search Bar or Menu here */}
            </div>
          </header>
          {children}
          <FloatingBasketSummary />
        </BasketProvider>
      </body>
    </html>
  );
}
