import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { BasketProvider } from '@/context/basket-context';
import { FloatingBasketSummary } from '@/components/floating-basket-summary';
import { AppNav } from '@/components/app-nav';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#2563eb" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="apple-mobile-web-app-title" content="Market Karşılaştırma" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <BasketProvider>
          <Suspense fallback={null}>
            <AppNav />
          </Suspense>
          {/* Mobil alt menü için içerik alanına padding */}
          <main className="pb-16 md:pb-0">
            {children}
          </main>
          <FloatingBasketSummary />
        </BasketProvider>
      </body>
    </html>
  );
}
